### ISSUE TITLE
How to upload firmware on the camera

### ISSUE THREAD

**Issue by simonachmueller** [openlux/microlux#2]
I was able to build your firmware, but I am not really familiar with CY7C68013A, can you describe how can I upload the firmware on the CY7C68013 chip?

**Comment by jonathanedgecombe** [comment]
If you're using windows then you can use the CyControl application included in the devkit software to upload the firmware, there's a download link to that on this page https://www.cypress.com/documentation/development-kitsboards/cy3684-ez-usb-fx2lp-development-kit

You can use CyControl to upload the hex file straight to the chip's RAM, I'd recommend sticking to that while doing development. To upload it to the EEPROM you'll need to use the hex2bix utility, also included with the devkit, to convert it to the right file format for CyControl to upload.

If you're on linux then there is a utility called fx2load for uploading firmware, although I haven't used it myself.

**Comment by grahamedgecombe** [comment]
> If you're on linux then there is a utility called fx2load for uploading firmware, although I haven't used it myself.

you can just use the `make load` target on Linux

**Comment by simonachmueller** [comment]
Yup I am on linux. make load almost did the trick, but it gives me "Device not opened." message.
When I type dmesg:
[ 2470.540149] usb 2-1.2: new high-speed USB device number 15 using ehci-pci
[ 2470.632372] usb 2-1.2: New USB device found, idVendor=04b4, idProduct=8613
[ 2470.632382] usb 2-1.2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 2470.633031] usbtest 2-1.2:1.0: FX2 device
[ 2470.633040] usbtest 2-1.2:1.0: high-speed {control bulk-in bulk-out} tests (+alt)

make load:
_objcopy -I ihex -O binary build/microlux.ihx build/microlux.bix
fx2load -v 0x04b4 -p 0x8613 build/microlux.bix
Device not opened.
Put device in reset
Device not opened.
Error: -1
loading bix file of length: 16312
Device not opened.
Error: -1
Set device to run
Device not opened.
Error: -1
Device not opened._

I'm using cheap EZ-USB FX2LP board from China.

**Comment by simonachmueller** [comment]
Ok, I got the firmware loaded on my board, I need to unload the "usbtest" kernel module (same issue as described here https://sigrok.org/wiki/Lcsoft_Mini_Board in section "possible issues")
So if one gets this "device not opened" problem just unload usbtest module with  _sudo rmmod usbtest_
